"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const money = (v) => Number(v || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
const date = (v) => v ? new Date(v).toLocaleDateString("en-IN") : "-";
export default function PatientPortalPage() {
  const router = useRouter(); const [data, setData] = useState(null); const [error, setError] = useState(""); const [tab, setTab] = useState("home");
  useEffect(() => { fetch("/api/patient-portal/me", { cache: "no-store" }).then(async (r) => { const body = await r.json(); if (!r.ok) throw new Error(body.error); setData(body); }).catch((e) => setError(e.message)); }, []);
  function speak() { if (!data || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(`Hello ${data.patient.name}. You have ${data.reports.length} ready reports and ${data.bills.length} bills.`)); }
  async function logout() { await fetch("/api/patient-portal/logout", { method: "POST" }); router.replace("/patient"); }
  if (error) return <main style={shell}><div style={card}><h2>Session expired</h2><p>{error}</p><button style={primary} onClick={() => router.replace("/patient")}>Sign in again</button></div></main>;
  if (!data) return <main style={shell}><div style={card}>Loading your records...</div></main>;
  return <main style={shell}><div style={{ width: "100%", maxWidth: 900 }}>
    <header style={{ ...card, display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12, flexWrap: "wrap" }}><div><h1 style={{ margin: 0, fontSize: 25 }}>Hello, {data.patient.name}</h1><p style={{ margin: "5px 0", color: "#64748b" }}>{data.patient.patientId}</p></div><div style={{ display: "flex", gap: 8 }}><button style={secondary} onClick={speak}>🔊 Listen</button><button style={secondary} onClick={logout}>Logout</button></div></header>
    <nav style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 10, margin: "14px 0" }}>{[["home","🏠","Home"],["reports","📄","Reports"],["bills","🧾","Bills"]].map(([id,icon,label]) => <button key={id} onClick={() => setTab(id)} style={tab === id ? primary : secondary}><span style={{ fontSize: 26, display: "block" }}>{icon}</span>{label}</button>)}</nav>
    {tab === "home" && <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(220px,1fr))", gap: 14 }}><button style={{ ...card, border: "3px solid #0d9488", textAlign: "left", cursor: "pointer" }} onClick={() => setTab("reports")}><div style={{ fontSize: 42 }}>📄</div><h2>{data.reports.length} Reports Ready</h2><p>Tap to view your test results</p></button><button style={{ ...card, border: "3px solid #2563eb", textAlign: "left", cursor: "pointer" }} onClick={() => setTab("bills")}><div style={{ fontSize: 42 }}>🧾</div><h2>{data.bills.length} Bills</h2><p>Tap to view payments</p></button><div style={{ ...card, border: "3px solid #f59e0b", color: "inherit" }}><div style={{ fontSize: 42 }}>☎️</div><h2>Need Help?</h2><p>Call the laboratory using the number printed on your bill.</p></div></section>}
    {tab === "reports" && <section style={{ display: "grid", gap: 14 }}>{data.reports.map((report) => <article key={report._id} style={card}><div style={{ display: "flex", justifyContent: "space-between", gap: 10 }}><div><h2 style={{ margin: 0 }}>{report.testSnapshot?.name || "Lab Report"}</h2><p>{report.reportId} · Released {date(report.releasedAt)}</p></div><span style={{ color: "#166534", fontWeight: 800 }}>READY</span></div><div style={{ overflowX: "auto" }}><table style={{ width: "100%", borderCollapse: "collapse" }}><thead><tr><th style={cell}>Test</th><th style={cell}>Result</th><th style={cell}>Expected range</th></tr></thead><tbody>{(report.results || []).map((r) => <tr key={r.key}><td style={cell}>{r.name}</td><td style={{ ...cell, fontWeight: 800 }}>{r.textValue || r.value || "-"} {r.unit || ""}</td><td style={cell}>{r.normalMin ?? "-"} – {r.normalMax ?? "-"}</td></tr>)}</tbody></table></div>{report.remarks && <p><strong>Lab remarks:</strong> {report.remarks}</p>}<p style={{ background: "#fffbeb", padding: 12, borderRadius: 8 }}>Please discuss results needing attention with your doctor. This portal does not provide a diagnosis.</p><button style={secondary} onClick={() => window.print()}>Print Report</button></article>)}{!data.reports.length && <div style={card}>No released reports yet.</div>}</section>}
    {tab === "bills" && <section style={{ display: "grid", gap: 14 }}>{data.bills.map((bill) => <article key={bill._id} style={card}><h2>{bill.billId}</h2><p>{date(bill.createdAt)} · {bill.tests.join(", ")}</p><div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, fontSize: 17 }}><span>Total</span><strong style={{ textAlign: "right" }}>₹{money(bill.totalAmount)}</strong><span>Paid</span><strong style={{ textAlign: "right", color: "#166534" }}>₹{money(bill.paidAmount)}</strong><span>Balance</span><strong style={{ textAlign: "right", color: "#b91c1c" }}>₹{money(Math.max(0, bill.totalAmount - bill.paidAmount))}</strong><span>Status</span><strong style={{ textAlign: "right" }}>{bill.billingStatus}</strong></div><h3>Receipts</h3>{data.receipts.filter((r) => String(r.invoiceId) === String(bill._id)).map((r) => <p key={r._id}>₹{money(r.amount)} · {r.method} · {date(r.receivedAt)}{r.isRefunded ? " · Refunded" : ""}</p>)}</article>)}{!data.bills.length && <div style={card}>No bills available.</div>}</section>}
  </div></main>;
}
const shell = { minHeight: "100vh", background: "#f0fdfa", padding: "16px", display: "flex", justifyContent: "center", fontFamily: "Arial,sans-serif" }; const card = { background: "white", borderRadius: 16, padding: 20, boxShadow: "0 6px 20px rgba(15,118,110,.08)" }; const primary = { minHeight: 58, border: 0, borderRadius: 12, background: "#0d9488", color: "white", padding: "10px 14px", fontSize: 17, fontWeight: 800, cursor: "pointer" }; const secondary = { minHeight: 50, border: "2px solid #94a3b8", borderRadius: 12, background: "white", padding: "8px 14px", fontSize: 16, fontWeight: 800, cursor: "pointer" }; const cell = { borderBottom: "1px solid #e2e8f0", padding: "12px 8px", textAlign: "left" };
